/**
 * productization.js — P33: Productization & Interop
 *
 * Modules:
 *   P33-01: exportController      — C / Python / MATLAB codegen
 *   P33-02: generateDesignReport  — HTML design report
 *   P33-03: toPythonControl /
 *            fromPythonControl    — JSON interchange with python-control
 *   P33-04: designWizard          — spec → workflow recommender
 */

// ══════════════════════════════════════════════════════════════════════════════
// P33-01: Controller Code Export
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Export a designed controller to executable code in C, Python, or MATLAB.
 *
 * Supported controller shapes:
 *   PID   — { type:'pid', Kp, Ki, Kd, N?, Ts? }
 *   TF    — { type:'tf',  num:number[], den:number[], Ts? }
 *   SS    — { type:'ss',  A, B, C, D, Ts? }
 *   SF    — { type:'sf',  K:number[], Ts? }     (state-feedback gain row vector)
 *
 * For continuous controllers, a discrete step (Euler / bilinear) is generated
 * automatically if `opts.Ts` is provided.
 *
 * @param {object}  ctrl          Controller descriptor (see above).
 * @param {'c'|'python'|'matlab'} target  Target language.
 * @param {object}  [opts]
 * @param {number}  [opts.Ts]     Sample time override (s).
 * @param {string}  [opts.varName='ctrl']  Variable/function name in generated code.
 * @param {boolean} [opts.includeHeader=true]  Emit file-header comment.
 * @returns {{ code: string, language: string, warnings: string[] }}
 */
export function exportController(ctrl, target, opts = {}) {
  if (!ctrl || typeof ctrl !== 'object') throw new Error('ctrl must be an object');
  const lang = (target || '').toLowerCase();
  if (!['c', 'python', 'matlab'].includes(lang)) {
    throw new Error(`Unsupported target "${target}". Use 'c', 'python', or 'matlab'.`);
  }

  const varName   = opts.varName ?? 'ctrl';
  const Ts        = opts.Ts ?? ctrl.Ts ?? null;
  const header    = opts.includeHeader !== false;
  const warnings  = [];

  const type = (ctrl.type || '').toLowerCase();

  switch (type) {
    case 'pid': return _exportPID(ctrl, lang, { varName, Ts, header, warnings });
    case 'tf':  return _exportTF(ctrl, lang, { varName, Ts, header, warnings });
    case 'ss':  return _exportSS(ctrl, lang, { varName, Ts, header, warnings });
    case 'sf':  return _exportSF(ctrl, lang, { varName, Ts, header, warnings });
    default:
      throw new Error(`Unknown controller type "${ctrl.type}". Supported: pid, tf, ss, sf.`);
  }
}

// ── helpers ──────────────────────────────────────────────────────────────────

function _fmt(x, digits = 8) {
  if (!Number.isFinite(x)) return String(x);
  // Use fixed if magnitude reasonable, otherwise exponential
  const abs = Math.abs(x);
  if (abs === 0) return '0.0';
  if (abs < 1e-4 || abs >= 1e7) return x.toExponential(digits);
  return x.toPrecision(digits + 1).replace(/\.?0+$/, '').replace(/^(\d+)$/, '$1.0');
}

function _arr(arr, digits = 8) {
  return arr.map((v) => _fmt(v, digits)).join(', ');
}

function _mat2c(mat) {
  return mat.map((row) => row.map((v) => _fmt(v)).join(', ')).join(',\n    ');
}

function _fileHdr(lang, desc) {
  const cmt = lang === 'c' ? '//' : lang === 'matlab' ? '%' : '#';
  const ts  = new Date().toISOString().slice(0, 10);
  return `${cmt} Auto-generated by ControlStudio P33 — ${ts}\n${cmt} ${desc}\n\n`;
}

// ── PID ──────────────────────────────────────────────────────────────────────

function _exportPID(ctrl, lang, { varName, Ts, header, warnings }) {
  const { Kp = 1, Ki = 0, Kd = 0, N = 100 } = ctrl;
  const discrete = Ts !== null;

  let code = header ? _fileHdr(lang, `PID controller — Kp=${Kp} Ki=${Ki} Kd=${Kd} N=${N}`) : '';

  if (lang === 'c') {
    if (discrete) {
      // Bilinear (Tustin) discrete PID
      const Ts_ = Ts;
      const Ki2 = Ki * Ts_ / 2;
      const Kd2 = Kd * N / (1 + N * Ts_ / 2);
      code += `/* Discrete PID (Tustin, Ts=${Ts_}s) */\n`;
      code += `typedef struct {\n`;
      code += `  double prev_e, prev_u_i, prev_u_d, prev_e_d;\n`;
      code += `} ${varName}_state_t;\n\n`;
      code += `double ${varName}_step(${varName}_state_t *s, double e) {\n`;
      code += `  double u_p = ${_fmt(Kp)} * e;\n`;
      code += `  double u_i = s->prev_u_i + ${_fmt(Ki2)} * (e + s->prev_e);\n`;
      code += `  double b   = ${_fmt(2 * Kd2 / Ts_)};\n`;
      code += `  double u_d = b * (e - s->prev_e) - s->prev_u_d * ${_fmt(N * Ts_ / 2 - 1)};\n`;
      code += `  s->prev_e   = e;\n`;
      code += `  s->prev_u_i = u_i;\n`;
      code += `  s->prev_u_d = u_d;\n`;
      code += `  return u_p + u_i + u_d;\n`;
      code += `}\n`;
    } else {
      warnings.push('Continuous PID: C code uses Euler integration; provide opts.Ts for bilinear.');
      code += `/* Continuous PID (Euler approx.) — provide Ts for proper discretization */\n`;
      code += `typedef struct { double integral, prev_e; } ${varName}_state_t;\n\n`;
      code += `double ${varName}_step(${varName}_state_t *s, double e, double dt) {\n`;
      code += `  s->integral += e * dt;\n`;
      code += `  double deriv = (e - s->prev_e) / (dt + 1e-12);\n`;
      code += `  s->prev_e = e;\n`;
      code += `  return ${_fmt(Kp)}*e + ${_fmt(Ki)}*s->integral + ${_fmt(Kd)}*deriv;\n`;
      code += `}\n`;
    }
  } else if (lang === 'python') {
    code += `import numpy as np\n\n`;
    code += `class ${_pyName(varName)}:\n`;
    code += `    """PID: Kp=${Kp}, Ki=${Ki}, Kd=${Kd}, N=${N}"""\n`;
    if (discrete) {
      code += `    Ts = ${Ts}\n\n`;
      code += `    def __init__(self):\n`;
      code += `        self.integral = 0.0\n`;
      code += `        self.prev_e   = 0.0\n\n`;
      code += `    def step(self, e):\n`;
      code += `        self.integral += e * self.Ts\n`;
      code += `        deriv = (e - self.prev_e) / (self.Ts + 1e-12)\n`;
      code += `        self.prev_e = e\n`;
      code += `        return ${_fmt(Kp)}*e + ${_fmt(Ki)}*self.integral + ${_fmt(Kd)}*deriv\n`;
    } else {
      code += `\n    def __init__(self):\n`;
      code += `        self.integral = 0.0\n`;
      code += `        self.prev_e   = 0.0\n\n`;
      code += `    def step(self, e, dt):\n`;
      code += `        self.integral += e * dt\n`;
      code += `        deriv = (e - self.prev_e) / (dt + 1e-12)\n`;
      code += `        self.prev_e = e\n`;
      code += `        return ${_fmt(Kp)}*e + ${_fmt(Ki)}*self.integral + ${_fmt(Kd)}*deriv\n`;
    }
  } else {
    // matlab
    code += `function u = ${varName}_step(e, state)\n`;
    code += `% PID: Kp=${Kp}, Ki=${Ki}, Kd=${Kd}, N=${N}\n`;
    if (discrete) {
      code += `Ts = ${Ts};\n`;
      code += `u = ${_fmt(Kp)}*e + ${_fmt(Ki)}*Ts*state.integral + ${_fmt(Kd)}/Ts*(e - state.prev_e);\n`;
    } else {
      code += `u = ${_fmt(Kp)}*e + ${_fmt(Ki)}*state.integral + ${_fmt(Kd)}*state.deriv;\n`;
    }
    code += `end\n`;
  }

  return { code, language: lang, warnings };
}

// ── TF ───────────────────────────────────────────────────────────────────────

function _exportTF(ctrl, lang, { varName, Ts, header, warnings }) {
  const num = ctrl.num ?? [1];
  const den = ctrl.den ?? [1];
  const discrete = Ts !== null || ctrl.Ts != null;
  const Ts_ = Ts ?? ctrl.Ts;

  let code = header ? _fileHdr(lang, `TF: num=[${_arr(num)}] / den=[${_arr(den)}]${discrete ? ` Ts=${Ts_}` : ''}`) : '';

  if (lang === 'c') {
    // Direct Form II transposed
    const n = Math.max(num.length, den.length) - 1; // order
    code += `/* Transfer function — Direct Form II transposed */\n`;
    code += `#define ${varName.toUpperCase()}_ORDER ${n}\n`;
    code += `static const double ${varName}_num[] = {${_arr(_padLeft(num, n + 1))}};\n`;
    code += `static const double ${varName}_den[] = {${_arr(_padLeft(den, n + 1))}};\n\n`;
    code += `typedef struct { double w[${n + 1}]; } ${varName}_state_t;\n\n`;
    code += `double ${varName}_step(${varName}_state_t *s, double u) {\n`;
    code += `  double a0 = ${varName}_den[0];\n`;
    code += `  double y  = (${varName}_num[0]/a0)*u + s->w[0];\n`;
    code += `  for (int i = 0; i < ${n}; i++) {\n`;
    code += `    s->w[i] = (${varName}_num[i+1]/a0)*u - (${varName}_den[i+1]/a0)*y\n`;
    code += `              + (i+1 < ${n} ? s->w[i+1] : 0.0);\n`;
    code += `  }\n`;
    code += `  return y;\n`;
    code += `}\n`;
    if (!discrete) warnings.push('Continuous TF exported as-is; ensure pre-discretized coefficients for real-time use.');
  } else if (lang === 'python') {
    code += `import numpy as np\n`;
    code += `from scipy.signal import lfilter, tf2ss\n\n`;
    code += `# Transfer function coefficients\n`;
    code += `num_${varName} = np.array([${_arr(num)}])\n`;
    code += `den_${varName} = np.array([${_arr(den)}])\n\n`;
    if (discrete) {
      code += `# Discrete-time filter (Ts=${Ts_})\n`;
      code += `class ${_pyName(varName)}:\n`;
      code += `    def __init__(self):\n`;
      code += `        self._zi = np.zeros(max(len(num_${varName}), len(den_${varName})) - 1)\n\n`;
      code += `    def step(self, u_sample):\n`;
      code += `        y, self._zi = lfilter(num_${varName}, den_${varName},\n`;
      code += `                              [u_sample], zi=self._zi)\n`;
      code += `        return float(y[0])\n`;
    } else {
      code += `# Continuous TF — convert to state-space for simulation\n`;
      code += `A, B, C, D = tf2ss(num_${varName}, den_${varName})\n`;
    }
  } else {
    // matlab
    code += `% Transfer function\n`;
    if (discrete) {
      code += `${varName} = tf([${_arr(num)}], [${_arr(den)}], ${Ts_});\n`;
    } else {
      code += `s = tf('s');\n`;
      code += `${varName} = tf([${_arr(num)}], [${_arr(den)}]);\n`;
    }
  }

  return { code, language: lang, warnings };
}

// ── SS ───────────────────────────────────────────────────────────────────────

function _exportSS(ctrl, lang, { varName, Ts, header, warnings }) {
  const A = ctrl.A, B = ctrl.B, C = ctrl.C, D = ctrl.D;
  if (!A || !B || !C || !D) throw new Error('SS controller requires A, B, C, D matrices.');
  const n = A.length;
  const m = B[0]?.length ?? 1;
  const p = C.length;
  const discrete = Ts !== null || ctrl.Ts != null;
  const Ts_ = Ts ?? ctrl.Ts;

  let code = header ? _fileHdr(lang, `State-space: n=${n}, m=${m}, p=${p}${discrete ? ` Ts=${Ts_}` : ''}`) : '';

  if (lang === 'c') {
    code += `/* State-space controller — n=${n} states, m=${m} inputs, p=${p} outputs */\n`;
    code += `#define ${varName.toUpperCase()}_N ${n}\n`;
    code += `#define ${varName.toUpperCase()}_M ${m}\n`;
    code += `#define ${varName.toUpperCase()}_P ${p}\n\n`;
    code += `static const double ${varName}_A[${n}][${n}] = {\n    {${_mat2c(A)}}\n};\n`;
    code += `static const double ${varName}_B[${n}][${m}] = {\n    {${_mat2c(B)}}\n};\n`;
    code += `static const double ${varName}_C[${p}][${n}] = {\n    {${_mat2c(C)}}\n};\n`;
    code += `static const double ${varName}_D[${p}][${m}] = {\n    {${_mat2c(D)}}\n};\n\n`;
    code += `typedef struct { double x[${n}]; } ${varName}_state_t;\n\n`;
    code += `void ${varName}_step(${varName}_state_t *s, const double u[${m}], double y[${p}]) {\n`;
    code += `  double xn[${n}] = {0};\n`;
    code += `  /* y = C*x + D*u */\n`;
    code += `  for (int i = 0; i < ${p}; i++) {\n`;
    code += `    y[i] = 0;\n`;
    code += `    for (int j = 0; j < ${n}; j++) y[i] += ${varName}_C[i][j] * s->x[j];\n`;
    code += `    for (int j = 0; j < ${m}; j++) y[i] += ${varName}_D[i][j] * u[j];\n`;
    code += `  }\n`;
    code += `  /* x+ = A*x + B*u */\n`;
    code += `  for (int i = 0; i < ${n}; i++) {\n`;
    code += `    for (int j = 0; j < ${n}; j++) xn[i] += ${varName}_A[i][j] * s->x[j];\n`;
    code += `    for (int j = 0; j < ${m}; j++) xn[i] += ${varName}_B[i][j] * u[j];\n`;
    code += `  }\n`;
    code += `  for (int i = 0; i < ${n}; i++) s->x[i] = xn[i];\n`;
    code += `}\n`;
    if (!discrete) warnings.push('Continuous SS exported; embed in ODE solver or pre-discretize.');
  } else if (lang === 'python') {
    code += `import numpy as np\n\n`;
    code += `class ${_pyName(varName)}:\n`;
    code += `    """State-space: n=${n}, m=${m}, p=${p}${discrete ? ', discrete Ts=' + Ts_ : ''}"""\n`;
    code += `    A = np.array(${_mat2py(A)})\n`;
    code += `    B = np.array(${_mat2py(B)})\n`;
    code += `    C = np.array(${_mat2py(C)})\n`;
    code += `    D = np.array(${_mat2py(D)})\n\n`;
    code += `    def __init__(self):\n`;
    code += `        self.x = np.zeros(${n})\n\n`;
    code += `    def step(self, u):\n`;
    code += `        u = np.atleast_1d(u)\n`;
    code += `        y = self.C @ self.x + self.D @ u\n`;
    code += `        self.x = self.A @ self.x + self.B @ u\n`;
    code += `        return y\n`;
  } else {
    // matlab
    code += `% State-space controller\n`;
    code += `A = [${A.map((r) => r.map(_fmt).join(' ')).join('; ')}];\n`;
    code += `B = [${B.map((r) => r.map(_fmt).join(' ')).join('; ')}];\n`;
    code += `C = [${C.map((r) => r.map(_fmt).join(' ')).join('; ')}];\n`;
    code += `D = [${D.map((r) => r.map(_fmt).join(' ')).join('; ')}];\n`;
    if (discrete) {
      code += `${varName} = ss(A, B, C, D, ${Ts_});\n`;
    } else {
      code += `${varName} = ss(A, B, C, D);\n`;
    }
  }

  return { code, language: lang, warnings };
}

// ── State-feedback gain ───────────────────────────────────────────────────────

function _exportSF(ctrl, lang, { varName, Ts, header, warnings }) {
  const K = ctrl.K ?? [];
  const n = K.length;

  let code = header ? _fileHdr(lang, `State-feedback gain K=[${_arr(K)}]`) : '';

  if (lang === 'c') {
    code += `static const double ${varName}_K[${n}] = {${_arr(K)}};\n\n`;
    code += `double ${varName}_step(const double x[${n}]) {\n`;
    code += `  double u = 0;\n`;
    code += `  for (int i = 0; i < ${n}; i++) u -= ${varName}_K[i] * x[i];\n`;
    code += `  return u;\n}\n`;
  } else if (lang === 'python') {
    code += `import numpy as np\n`;
    code += `K_${varName} = np.array([${_arr(K)}])\n\n`;
    code += `def ${_pyName(varName)}_step(x):\n`;
    code += `    return float(-K_${varName} @ np.atleast_1d(x))\n`;
  } else {
    code += `K = [${_arr(K)}];\n`;
    code += `u = -K * x;  %% state-feedback: u = -Kx\n`;
  }

  return { code, language: lang, warnings };
}

// ── util ──────────────────────────────────────────────────────────────────────

function _padLeft(arr, n) {
  const out = new Array(n).fill(0);
  const offset = n - arr.length;
  for (let i = 0; i < arr.length; i++) out[offset + i] = arr[i];
  return out;
}

function _pyName(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function _mat2py(mat) {
  return '[' + mat.map((row) => '[' + row.map(_fmt).join(', ') + ']').join(', ') + ']';
}

// ══════════════════════════════════════════════════════════════════════════════
// P33-02: HTML Design Report
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Generate an HTML design report from analysis results.
 *
 * The `design` object can contain any subset of:
 *   title       — string
 *   description — string
 *   margins     — { phaseMargin, gainMargin, gainCrossover, phaseFreq }
 *   poles       — number[][]  [[re,im], ...]
 *   zeros       — number[][]
 *   stepResponse — { time: number[], output: number[], overshoot?, settlingTime?, riseTime? }
 *   params      — { [key]: value }  arbitrary param table
 *   sections    — [{ title, content }]  freeform HTML sections
 *   warnings    — string[]
 *
 * @param {object}  design
 * @param {object}  [opts]
 * @param {string}  [opts.theme='light']  'light' | 'dark'
 * @param {boolean} [opts.includeCSS=true]
 * @returns {{ html: string, sections: string[] }}
 */
export function generateDesignReport(design, opts = {}) {
  const title  = design.title ?? 'Control Design Report';
  const theme  = opts.theme ?? 'light';
  const css    = opts.includeCSS !== false;
  const date   = new Date().toISOString().slice(0, 10);
  const sects  = [];

  const bg  = theme === 'dark' ? '#1a1a2e' : '#ffffff';
  const fg  = theme === 'dark' ? '#e0e0e0' : '#1a1a2e';
  const acc = theme === 'dark' ? '#4ade80' : '#1d6f42';
  const tbl = theme === 'dark' ? '#2a2a3e' : '#f0f4f8';

  let html = `<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n`;
  html += `<meta name="viewport" content="width=device-width, initial-scale=1">\n`;
  html += `<title>${_esc(title)}</title>\n`;

  if (css) {
    html += `<style>\n`;
    html += `body{background:${bg};color:${fg};font-family:system-ui,sans-serif;`;
    html += `max-width:900px;margin:0 auto;padding:2rem;line-height:1.6}\n`;
    html += `h1{color:${acc};border-bottom:2px solid ${acc};padding-bottom:.4rem}\n`;
    html += `h2{color:${acc};margin-top:2rem}\n`;
    html += `table{border-collapse:collapse;width:100%;margin:.8rem 0}\n`;
    html += `th,td{padding:.5rem 1rem;text-align:left;border:1px solid ${acc}30}\n`;
    html += `th{background:${acc}22;font-weight:600}\n`;
    html += `tr:nth-child(even){background:${tbl}}\n`;
    html += `.pass{color:#4ade80}.fail{color:#f87171}.warn{color:#fbbf24}\n`;
    html += `.badge{display:inline-block;padding:.15rem .5rem;border-radius:.25rem;`;
    html += `font-size:.8rem;font-weight:700}\n`;
    html += `.badge-ok{background:#16a34a22;color:#4ade80}`;
    html += `.badge-warn{background:#92400e22;color:#fbbf24}`;
    html += `.badge-fail{background:#7f1d1d22;color:#f87171}\n`;
    html += `pre{background:${tbl};padding:1rem;border-radius:.5rem;overflow-x:auto;font-size:.85rem}\n`;
    html += `footer{margin-top:3rem;font-size:.8rem;color:${fg}66;text-align:center}\n`;
    html += `</style>\n`;
  }

  html += `</head>\n<body>\n`;
  html += `<h1>${_esc(title)}</h1>\n`;
  html += `<p><strong>Generated:</strong> ${date}</p>\n`;

  if (design.description) {
    html += `<p>${_esc(design.description)}</p>\n`;
    sects.push('description');
  }

  // ── Stability Margins ────────────────────────────────────────────────────
  if (design.margins) {
    const m  = design.margins;
    const pm = Number.isFinite(m.phaseMargin)  ? m.phaseMargin.toFixed(2)  : '—';
    const gm = Number.isFinite(m.gainMargin)   ? m.gainMargin.toFixed(2)   : '—';
    const wc = Number.isFinite(m.gainCrossover) ? m.gainCrossover.toFixed(4) : '—';
    const wp = Number.isFinite(m.phaseFreq)    ? m.phaseFreq.toFixed(4)    : '—';
    const pmOk = Number(pm) >= 30;
    const gmOk = Number(gm) >= 6;
    html += `<h2>Stability Margins</h2>\n`;
    html += `<table><thead><tr><th>Metric</th><th>Value</th><th>Status</th></tr></thead><tbody>\n`;
    html += `<tr><td>Phase Margin</td><td>${pm}°</td><td>${_badge(pmOk ? 'ok' : 'warn', pm + '°')}</td></tr>\n`;
    html += `<tr><td>Gain Margin</td><td>${gm} dB</td><td>${_badge(gmOk ? 'ok' : 'warn', gm + ' dB')}</td></tr>\n`;
    html += `<tr><td>Gain Crossover ω<sub>c</sub></td><td>${wc} rad/s</td><td>—</td></tr>\n`;
    html += `<tr><td>Phase Crossover ω<sub>π</sub></td><td>${wp} rad/s</td><td>—</td></tr>\n`;
    html += `</tbody></table>\n`;
    sects.push('margins');
  }

  // ── Poles & Zeros ────────────────────────────────────────────────────────
  if (design.poles?.length) {
    html += `<h2>Closed-Loop Poles</h2>\n`;
    html += `<table><thead><tr><th>#</th><th>Real</th><th>Imag</th><th>Stable</th></tr></thead><tbody>\n`;
    design.poles.forEach(([re, im], i) => {
      const stable = re < 0;
      html += `<tr><td>${i + 1}</td><td>${_fmt(re)}</td><td>${_fmt(im)}</td>`;
      html += `<td>${_badge(stable ? 'ok' : 'fail', stable ? 'STABLE' : 'UNSTABLE')}</td></tr>\n`;
    });
    html += `</tbody></table>\n`;
    sects.push('poles');
  }

  if (design.zeros?.length) {
    html += `<h2>Open-Loop Zeros</h2>\n`;
    html += `<table><thead><tr><th>#</th><th>Real</th><th>Imag</th></tr></thead><tbody>\n`;
    design.zeros.forEach(([re, im], i) => {
      html += `<tr><td>${i + 1}</td><td>${_fmt(re)}</td><td>${_fmt(im)}</td></tr>\n`;
    });
    html += `</tbody></table>\n`;
    sects.push('zeros');
  }

  // ── Step Response Metrics ────────────────────────────────────────────────
  if (design.stepResponse) {
    const sr = design.stepResponse;
    html += `<h2>Step Response Metrics</h2>\n`;
    html += `<table><thead><tr><th>Metric</th><th>Value</th></tr></thead><tbody>\n`;
    if (Number.isFinite(sr.overshoot))
      html += `<tr><td>Overshoot</td><td>${sr.overshoot.toFixed(2)}%</td></tr>\n`;
    if (Number.isFinite(sr.settlingTime))
      html += `<tr><td>Settling Time (2%)</td><td>${sr.settlingTime.toFixed(4)} s</td></tr>\n`;
    if (Number.isFinite(sr.riseTime))
      html += `<tr><td>Rise Time (10→90%)</td><td>${sr.riseTime.toFixed(4)} s</td></tr>\n`;
    if (Number.isFinite(sr.steadyState))
      html += `<tr><td>Steady-State</td><td>${sr.steadyState.toFixed(6)}</td></tr>\n`;
    html += `</tbody></table>\n`;

    // ASCII sparkline
    if (Array.isArray(sr.time) && Array.isArray(sr.output) && sr.time.length > 0) {
      html += `<details><summary>Step Response Data (${sr.time.length} points)</summary>\n<pre>`;
      const COLS = 60, ROWS = 12;
      const tMax = sr.time[sr.time.length - 1];
      const yMax = Math.max(...sr.output, 1e-9);
      const yMin = Math.min(...sr.output, 0);
      const yRange = yMax - yMin || 1;
      // Reduce to COLS points
      const step = Math.max(1, Math.floor(sr.time.length / COLS));
      const grid = Array.from({ length: ROWS }, () => Array(COLS).fill(' '));
      for (let i = 0; i < COLS; i++) {
        const idx = Math.min(i * step, sr.output.length - 1);
        const row = ROWS - 1 - Math.round(((sr.output[idx] - yMin) / yRange) * (ROWS - 1));
        const clampedRow = Math.max(0, Math.min(ROWS - 1, row));
        grid[clampedRow][i] = '█';
      }
      // y-axis labels
      html += `y=${yMax.toFixed(3)} |`;
      grid.forEach((row, ri) => {
        html += row.join('');
        if (ri < ROWS - 1) {
          const yVal = yMax - (ri + 1) * yRange / ROWS;
          html += `\n${ri === Math.floor(ROWS / 2) ? 'y=' + yVal.toFixed(3) + ' |' : '       |'}`;
        }
      });
      html += `\n       +${'-'.repeat(COLS)} t → ${tMax.toFixed(3)}s\n</pre></details>\n`;
    }
    sects.push('stepResponse');
  }

  // ── Arbitrary params table ───────────────────────────────────────────────
  if (design.params && Object.keys(design.params).length > 0) {
    html += `<h2>Design Parameters</h2>\n`;
    html += `<table><thead><tr><th>Parameter</th><th>Value</th></tr></thead><tbody>\n`;
    for (const [k, v] of Object.entries(design.params)) {
      html += `<tr><td>${_esc(k)}</td><td>${_esc(String(v))}</td></tr>\n`;
    }
    html += `</tbody></table>\n`;
    sects.push('params');
  }

  // ── Freeform sections ────────────────────────────────────────────────────
  if (Array.isArray(design.sections)) {
    for (const sec of design.sections) {
      html += `<h2>${_esc(sec.title ?? '')}</h2>\n${sec.content ?? ''}\n`;
      sects.push(sec.title ?? 'section');
    }
  }

  // ── Warnings ─────────────────────────────────────────────────────────────
  if (design.warnings?.length) {
    html += `<h2>Warnings</h2>\n<ul>\n`;
    for (const w of design.warnings) {
      html += `  <li class="warn">Warning: ${_esc(w)}</li>\n`;
    }
    html += `</ul>\n`;
    sects.push('warnings');
  }

  html += `<footer>ControlStudio P33 — Auto-generated report</footer>\n`;
  html += `</body>\n</html>\n`;

  return { html, sections: sects };
}

function _badge(kind, text) {
  return `<span class="badge badge-${kind}">${_esc(String(text))}</span>`;
}

function _esc(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ══════════════════════════════════════════════════════════════════════════════
// P33-03: python-control JSON Bridge
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Serialize a ControlStudio object to a JSON structure compatible with
 * python-control's to_dict / from_dict convention.
 *
 * Supported input shapes:
 *   { type:'tf',  num, den, Ts? }
 *   { type:'ss',  A, B, C, D, Ts? }
 *   { type:'pid', Kp, Ki, Kd, N?, Ts? }  → converted to TF first
 *
 * python-control convention (StateSpace.to_dict):
 *   { type: 'StateSpace', A, B, C, D, dt }   dt=0 for continuous
 *   { type: 'TransferFunction', num, den, dt }
 *
 * @param {object}  obj  ControlStudio controller/model descriptor.
 * @returns {object}  Plain JSON-serializable object.
 */
export function toPythonControl(obj) {
  if (!obj || typeof obj !== 'object') throw new Error('obj must be an object');
  const type = (obj.type || '').toLowerCase();
  const dt   = obj.Ts ?? 0;

  if (type === 'tf') {
    return {
      type: 'TransferFunction',
      num:  [obj.num ?? [1]],   // python-control wraps each channel: num[i][j] = row i, col j
      den:  [obj.den ?? [1]],
      dt,
    };
  }

  if (type === 'ss') {
    if (!obj.A || !obj.B || !obj.C || !obj.D) throw new Error('SS requires A,B,C,D');
    return {
      type: 'StateSpace',
      A: obj.A,
      B: obj.B,
      C: obj.C,
      D: obj.D,
      dt,
    };
  }

  if (type === 'pid') {
    // Convert PID to TF, then serialize
    const { Kp = 1, Ki = 0, Kd = 0, N = 100 } = obj;
    // C(s) numerator/denominator in continuous time
    // = [Kd*N + Kp, Kp*N + Ki, Ki*N] / [1, N, 0]
    const num = [Kd * N + Kp, Kp * N + Ki, Ki * N];
    const den = [1, N, 0];
    return {
      type:     'TransferFunction',
      num:      [num],
      den:      [den],
      dt,
      _source:  { type: 'PID', Kp, Ki, Kd, N },
    };
  }

  throw new Error(`toPythonControl: unsupported type "${obj.type}"`);
}

/**
 * Deserialize a python-control JSON dict back to a ControlStudio descriptor.
 *
 * @param {object}  data  JSON from python-control to_dict / from toPythonControl.
 * @returns {object}  ControlStudio descriptor { type, ..., Ts? }
 */
export function fromPythonControl(data) {
  if (!data || typeof data !== 'object') throw new Error('data must be an object');
  const type = data.type ?? '';
  const Ts   = (data.dt && data.dt !== 0) ? data.dt : undefined;

  if (type === 'TransferFunction') {
    // python-control stores num/den as nested arrays [[coeffs]]
    const num = Array.isArray(data.num?.[0]) ? data.num[0] : (data.num ?? [1]);
    const den = Array.isArray(data.den?.[0]) ? data.den[0] : (data.den ?? [1]);
    const out = { type: 'tf', num, den };
    if (Ts !== undefined) out.Ts = Ts;
    if (data._source) {
      // Recover original PID if available
      const s = data._source;
      if (s.type === 'PID') return { type: 'pid', Kp: s.Kp, Ki: s.Ki, Kd: s.Kd, N: s.N, ...(Ts !== undefined ? { Ts } : {}) };
    }
    return out;
  }

  if (type === 'StateSpace') {
    if (!data.A || !data.B || !data.C || !data.D) throw new Error('StateSpace requires A,B,C,D');
    const out = { type: 'ss', A: data.A, B: data.B, C: data.C, D: data.D };
    if (Ts !== undefined) out.Ts = Ts;
    return out;
  }

  throw new Error(`fromPythonControl: unsupported type "${type}"`);
}

// ══════════════════════════════════════════════════════════════════════════════
// P33-04: Design Wizard
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Design Wizard — spec-driven controller architecture recommender.
 *
 * Takes a performance specification and returns:
 *   - Recommended controller type & order
 *   - Ordered design workflow steps
 *   - Estimated design complexity
 *   - Relevant ControlStudio API calls with parameters
 *
 * @param {object}  spec
 * @param {number}  [spec.overshoot]        Max % overshoot (e.g. 10)
 * @param {number}  [spec.settlingTime]     Settling time in seconds
 * @param {number}  [spec.bandwidth]        Target bandwidth in rad/s
 * @param {number}  [spec.phaseMargin]      Min phase margin in degrees (default 45)
 * @param {number}  [spec.gainMargin]       Min gain margin in dB (default 6)
 * @param {boolean} [spec.robustness]       True if parametric uncertainty matters
 * @param {boolean} [spec.nonlinear]        True for nonlinear plant
 * @param {boolean} [spec.safety]           True if hard safety constraints needed
 * @param {boolean} [spec.adaptive]         True if plant varies / unknown
 * @param {boolean} [spec.discrete]         True for embedded digital implementation
 * @param {number}  [spec.Ts]              Sample time (s), implies discrete
 * @param {'siso'|'mimo'} [spec.topology]  Default 'siso'
 * @param {number}  [spec.nInputs]         Number of control inputs (MIMO)
 * @param {number}  [spec.nOutputs]        Number of plant outputs (MIMO)
 *
 * @returns {{
 *   recommendation: string,
 *   controllerType: string,
 *   workflow: { step:number, action:string, api:string, note:string }[],
 *   complexity: 'low'|'medium'|'high'|'very-high',
 *   warnings: string[],
 *   alternatives: string[],
 * }}
 */
export function designWizard(spec = {}) {
  const {
    overshoot      = null,
    settlingTime   = null,
    bandwidth      = null,
    phaseMargin    = 45,
    gainMargin     = 6,
    robustness     = false,
    nonlinear      = false,
    safety         = false,
    adaptive       = false,
    discrete       = !!(spec.Ts),
    Ts             = null,
    topology       = 'siso',
    nInputs        = 1,
    nOutputs       = 1,
  } = spec;

  const warnings     = [];
  const alternatives = [];
  const workflow     = [];
  let   step         = 1;

  // ── Validate ────────────────────────────────────────────────────────────
  if (overshoot !== null && (overshoot < 0 || overshoot > 100)) {
    warnings.push('overshoot should be between 0 and 100 (%).');
  }
  if (settlingTime !== null && settlingTime <= 0) {
    warnings.push('settlingTime should be positive (seconds).');
  }
  if (discrete && !Ts) {
    warnings.push('discrete=true but Ts not specified; provide Ts for quantisation analysis.');
  }
  if (topology === 'mimo' && (nInputs < 2 || nOutputs < 2)) {
    warnings.push('MIMO topology selected but nInputs/nOutputs < 2; check dimensions.');
  }

  // ── Decide controller type ───────────────────────────────────────────────
  let ctrlType = 'PID';
  let complexity = 'low';
  let rec = '';

  const isMIMO      = topology === 'mimo' || nInputs > 1 || nOutputs > 1;
  const tightSpec   = (overshoot !== null && overshoot < 5) ||
                      (phaseMargin > 60) ||
                      (bandwidth !== null && bandwidth > 100);
  const relaxedSpec = overshoot === null && settlingTime === null && bandwidth === null;

  if (safety) {
    ctrlType   = nonlinear ? 'CLF-CBF (Nonlinear)' : 'MPC with Constraints';
    complexity = 'high';
    rec        = 'Hard safety constraints require a QP-based safety filter (CLF-CBF) or constrained MPC.';
    alternatives.push('Tube MPC', 'LPV with saturations');
  } else if (nonlinear && adaptive) {
    ctrlType   = 'MRAC or STR';
    complexity = 'very-high';
    rec        = 'Nonlinear + adaptive plant is the hardest case; MRAC with Lyapunov rule is most principled.';
    alternatives.push('Gain-scheduling', 'Feedback Linearization + RLS');
  } else if (nonlinear) {
    ctrlType   = 'Feedback Linearization';
    complexity = 'high';
    rec        = 'Nonlinear plant with differentially-flat output: use exact I/O linearization; then apply linear outer loop.';
    alternatives.push('Backstepping', 'Sliding Mode Control', 'Gain scheduling');
  } else if (adaptive) {
    ctrlType   = 'MRAC';
    complexity = 'high';
    rec        = 'Time-varying or uncertain plant: MRAC (MIT / Lyapunov rule) provides automatic parameter tracking.';
    alternatives.push('STR', 'RLS + gain scheduling');
  } else if (isMIMO && robustness) {
    ctrlType   = 'H∞ (MIMO)';
    complexity = 'high';
    rec        = 'MIMO plant with robustness requirements: synthesize H∞ controller via γ-iteration or D-K iteration (μ-synthesis) for structured uncertainty.';
    alternatives.push('LQR/LQG', 'LPV synthesis', 'D-K iteration');
  } else if (isMIMO) {
    ctrlType   = 'LQR/LQG';
    complexity = 'medium';
    rec        = 'MIMO plant without specific robustness requirements: LQR for full state, LQG (LQR+Kalman) for output feedback.';
    alternatives.push('H∞', 'Decentralised PID', 'MPC');
  } else if (robustness) {
    ctrlType   = 'H∞ Loop-shaping';
    complexity = 'medium';
    rec        = 'SISO with robustness emphasis: H∞ loop-shaping gives explicit ‖S‖∞ / ‖T‖∞ bounds.';
    alternatives.push('QFT (not in suite)', 'Lead-lag + gain margin');
  } else if (tightSpec) {
    ctrlType   = 'Lead-Lag / State-feedback';
    complexity = 'medium';
    rec        = 'Tight transient spec with no uncertainty: pole-placement or lead compensator design is most direct.';
    alternatives.push('PID (auto-tuned)', 'LQR');
  } else {
    ctrlType   = 'PID';
    complexity = 'low';
    rec        = 'Standard SISO regulation: PID with Ziegler–Nichols or SIMC tuning is a proven starting point.';
    alternatives.push('Lead-Lag', 'IMC');
  }

  // ── Build workflow ───────────────────────────────────────────────────────
  // Step 1: always identify / model plant
  workflow.push({
    step: step++,
    action: 'Plant identification / modelling',
    api: 'identifyRLS(n, opts) or identifySRIVC(y, u, na, nb, Ts)',
    note: 'Obtain LTI model G(s) or G(z). Validate with frequency-response data.',
  });

  // Step 2: stability analysis
  workflow.push({
    step: step++,
    action: 'Open-loop stability & frequency analysis',
    api: 'stabilityMargins(plant)',
    note: `Confirm PM ≥ ${phaseMargin}°, GM ≥ ${gainMargin} dB. Check BIBO and pole locations.`,
  });

  // Type-specific steps
  if (ctrlType === 'PID') {
    workflow.push({
      step: step++,
      action: 'SIMC/IMC auto-tuning',
      api: `designIMC(plant, { lambda: ${settlingTime ? (settlingTime * 0.1).toFixed(2) : 0.5} })`,
      note: 'Set filter time-constant λ to desired closed-loop bandwidth.',
    });
    workflow.push({
      step: step++,
      action: 'PID fine-tuning with GA (optional)',
      api: `gaTuner(plant, pidCost, { popSize:50, generations:100 })`,
      note: 'Optimise Kp/Ki/Kd for multi-objective (overshoot + settling + robustness).',
    });
  } else if (ctrlType.startsWith('Lead')) {
    if (overshoot !== null && settlingTime !== null) {
      workflow.push({
        step: step++,
        action: 'Map spec → target poles',
        api: `specsToTargetPoles({ overshoot:${overshoot}, settlingTime:${settlingTime} })`,
        note: 'Compute dominant pole ζ, ωn, target s = −σ ± jωd.',
      });
    }
    workflow.push({
      step: step++,
      action: 'Lead compensator design',
      api: `designLeadForPM(plant, { targetPM:${phaseMargin} })`,
      note: 'Lift phase margin; cascade lead if single stage insufficient.',
    });
  } else if (ctrlType === 'LQR/LQG') {
    workflow.push({
      step: step++,
      action: 'LQR state-feedback gain',
      api: `solveCARE(A, B, Q, R)  →  K`,
      note: 'Choose Q/R weights to balance performance vs. control effort.',
    });
    workflow.push({
      step: step++,
      action: 'Kalman filter observer',
      api: `kalmanFilter(A, C, Qn, Rn)`,
      note: 'Design observer for output-feedback; combine with LQR for LQG.',
    });
  } else if (ctrlType.startsWith('H∞')) {
    workflow.push({
      step: step++,
      action: 'H∞ synthesis via γ-iteration',
      api: `synthesizeHinf(P, { gamma: 1.2 })`,
      note: 'Start with γ=1.2×‖P‖∞; iterate down to γ_min.',
    });
    if (isMIMO && robustness) {
      workflow.push({
        step: step++,
        action: 'D-K iteration for μ-synthesis',
        api: `dkIteration(plant, { maxIterations:6 })`,
        note: 'Minimise μ upper bound for structured uncertainty; alternates K-step and D-step.',
      });
    }
  } else if (ctrlType === 'Feedback Linearization') {
    workflow.push({
      step: step++,
      action: 'Define nonlinear model f(x), g(x), h(x)',
      api: `feedbackLinearization(f, g, h, r, { k: [...] })`,
      note: 'Compute relative degree r; verify Lg·Lf^{r-1} h ≠ 0 (regularity).',
    });
    workflow.push({
      step: step++,
      action: 'Outer linear controller design',
      api: `specsToTargetPoles(...)  →  place k gains`,
      note: 'After exact linearization, design linear outer loop for tracking.',
    });
  } else if (ctrlType.startsWith('CLF-CBF') || ctrlType.startsWith('MPC')) {
    workflow.push({
      step: step++,
      action: 'Define Lyapunov function V(x) and barrier h(x)',
      api: `controlBarrierFunction(f, g, V, h, { gamma, alpha })`,
      note: 'Ensure h(x)≥0 is the safe set; choose α (class-K) for barrier tightness.',
    });
    if (ctrlType.startsWith('MPC')) {
      workflow.push({
        step: step++,
        action: 'Constrained MPC setup',
        api: `mpcController(model, { N:10, uMin, uMax, xMin, xMax })`,
        note: 'Horizon N≥5; add terminal cost / constraint for stability guarantee.',
      });
    }
  } else if (ctrlType.startsWith('MRAC')) {
    workflow.push({
      step: step++,
      action: 'Reference model selection',
      api: `designMRAC(refModel, { rule:'lyapunov', gammaR:0.5, gammaX:0.5 })`,
      note: 'Choose stable reference model matching desired closed-loop response.',
    });
  }

  // Discrete implementation (common last step)
  if (discrete || Ts) {
    workflow.push({
      step: step++,
      action: 'Discretize controller',
      api: `c2dTustin(ctrl, ${Ts ?? 0.01})`,
      note: `Sample at Ts=${Ts ?? '?'} s; bilinear (Tustin) preserves stability margin.`,
    });
  }

  // Validation step (always last)
  workflow.push({
    step: step++,
    action: 'Closed-loop simulation & validation',
    api: 'simulate(closedLoop, stepInput, { tEnd: 10 })',
    note: 'Verify overshoot, settling, and margin specs. Export report via generateDesignReport.',
  });

  return {
    recommendation: rec,
    controllerType: ctrlType,
    workflow,
    complexity,
    warnings,
    alternatives,
  };
}
