/**
 * tube_mpc.js — Phase 24-02 Tube MPC baseline.
 *
 * Implements a deterministic linear tube-MPC approximation:
 *   u_k = v_k - K(x_k - z_k)
 * where z is the nominal state, v is generated by the existing constrained MPC
 * engine with tightened input bounds, and the tube radius is propagated by
 * interval bounds under A_cl = A - BK.
 */

import {
  matMul,
  matSub,
} from '../math/matrix.js';
import {
  finiteHorizonLqr,
  firstMpcActionConstrained,
  validateMpcModel,
} from './mpc.js';

function cloneColumn(x) {
  return x.map((row) => [row[0]]);
}

function asColumn(x, name) {
  if (!Array.isArray(x)) throw new Error(`${name} must be an array`);
  if (Array.isArray(x[0])) return x.map((row) => [row[0]]);
  return x.map((value) => [value]);
}

function normalizeBound(bound, size, fallback) {
  if (bound == null) return Array(size).fill(fallback);
  return Array.isArray(bound) ? Array.from({ length: size }, (_, i) => bound[i] ?? fallback) : Array(size).fill(bound);
}

function absMatrixTimesVector(A, v) {
  return A.map((row) => row.reduce((sum, aij, j) => sum + Math.abs(aij) * v[j], 0));
}

function addColumns(A, B) {
  return A.map((row, i) => [row[0] + B[i][0]]);
}

function clampColumn(u, lower, upper) {
  return u.map((row, i) => [Math.min(upper[i], Math.max(lower[i], row[0]))]);
}

function controlTightening(K, radius) {
  return K.map((row) => row.reduce((sum, kij, j) => sum + Math.abs(kij) * radius[j], 0));
}

export function propagateTubeRadius(Ad, Bd, K, radius, disturbanceBound) {
  const Acl = matSub(Ad, matMul(Bd, K));
  const next = absMatrixTimesVector(Acl, radius);
  return next.map((value, i) => value + disturbanceBound[i]);
}

export function designTubeMpc(Ad, Bd, Q, R, horizon, constraints = {}, options = {}) {
  const { n, m } = validateMpcModel(Ad, Bd, Q, R, horizon);
  const feedback = options.K
    ? options.K
    : finiteHorizonLqr(Ad, Bd, Q, R, horizon, options.Qf ?? null, { autoTerminalCost: true }).firstGain;
  const K = feedback.map((row) => [...row]);
  const disturbanceBound = normalizeBound(options.disturbanceBound, n, 0);
  const initialRadius = normalizeBound(options.initialRadius, n, 0);
  const uMin = normalizeBound(constraints.uMin, m, -Infinity);
  const uMax = normalizeBound(constraints.uMax, m, Infinity);
  for (let i = 0; i < m; i++) {
    if (uMin[i] > uMax[i]) throw new Error(`Tube MPC input bound conflict at input ${i}`);
  }

  const radiusSchedule = [initialRadius];
  for (let k = 0; k < horizon; k++) {
    radiusSchedule.push(propagateTubeRadius(Ad, Bd, K, radiusSchedule[k], disturbanceBound));
  }

  const tightening = controlTightening(K, radiusSchedule[0]);
  const tightenedUMin = uMin.map((value, i) => Number.isFinite(value) ? value + tightening[i] : value);
  const tightenedUMax = uMax.map((value, i) => Number.isFinite(value) ? value - tightening[i] : value);
  const feasible = tightenedUMin.every((value, i) => value <= tightenedUMax[i] + 1e-10);

  return {
    K,
    disturbanceBound,
    radiusSchedule,
    tightening,
    tightenedConstraints: { uMin: tightenedUMin, uMax: tightenedUMax },
    feasible,
    diagnostics: feasible
      ? []
      : tightenedUMin.map((value, i) => value > tightenedUMax[i] ? {
          type: 'tightenedInputConflict',
          inputIndex: i,
          tightenedUMin: value,
          tightenedUMax: tightenedUMax[i],
        } : null).filter(Boolean),
  };
}

export function simulateTubeMPC(Ad, Bd, Q, R, horizon, x0, constraints = {}, options = {}) {
  const { n, m } = validateMpcModel(Ad, Bd, Q, R, horizon);
  const steps = options.steps ?? 30;
  const xInitial = asColumn(x0, 'x0');
  const design = designTubeMpc(Ad, Bd, Q, R, horizon, constraints, options);
  if (!design.feasible && options.throwOnInfeasible) {
    throw new Error('Tube MPC tightened constraints are infeasible');
  }

  const x = [cloneColumn(xInitial)];
  const z = [cloneColumn(options.z0 ? asColumn(options.z0, 'z0') : xInitial)];
  const u = [];
  const v = [];
  const e = [];
  const radius = [design.radiusSchedule[0]];
  const feasibleLog = [];
  const D = options.disturbanceFn ?? ((k) => normalizeBound(options.disturbance, n, 0).map((value) => [value]));
  const Qf = options.Qf ?? Q;

  for (let k = 0; k < steps; k++) {
    const eCol = matSub(x[k], z[k]);
    const tightened = design.tightenedConstraints;
    const action = firstMpcActionConstrained(Ad, Bd, Q, R, horizon, z[k], tightened, Qf, options);
    const vk = action.u;
    const correction = matMul(design.K, eCol);
    const ukUnclamped = matSub(vk, correction);
    const uMin = normalizeBound(constraints.uMin, m, -Infinity);
    const uMax = normalizeBound(constraints.uMax, m, Infinity);
    const uk = clampColumn(ukUnclamped, uMin, uMax);
    const wk = asColumn(D(k, x[k], uk), `disturbance(${k})`);
    const xNext = addColumns(addColumns(matMul(Ad, x[k]), matMul(Bd, uk)), wk);
    const zNext = addColumns(matMul(Ad, z[k]), matMul(Bd, vk));
    const nextRadius = propagateTubeRadius(Ad, Bd, design.K, radius[k], design.disturbanceBound);

    x.push(xNext);
    z.push(zNext);
    u.push(uk);
    v.push(vk);
    e.push(eCol);
    radius.push(nextRadius);
    feasibleLog.push({
      tightenedFeasible: design.feasible,
      actionConverged: action.converged,
      errorWithinTube: eCol.every((row, i) => Math.abs(row[0]) <= radius[k][i] + 1e-8),
    });
  }

  return {
    x,
    z,
    u,
    v,
    e,
    radius,
    K: design.K,
    tightenedConstraints: design.tightenedConstraints,
    feasible: design.feasible,
    diagnostics: design.diagnostics,
    feasibleLog,
    finalErrorNormInf: Math.max(...matSub(x[x.length - 1], z[z.length - 1]).map((row) => Math.abs(row[0]))),
    steps,
    horizon,
  };
}
